"""init auditoria schema

Revision ID: 116070621ddd
Revises: 
Create Date: 2026-01-26 12:51:48.484295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116070621ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('naviera', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    op.create_table('job_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['auditoria.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    op.create_table('result_charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('guia', sa.String(length=50), nullable=False),
    sa.Column('contenedor', sa.String(length=20), nullable=True),
    sa.Column('tipo_cargo', sa.String(length=120), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('naviera', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['auditoria.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    with op.batch_alter_table('result_charge', schema='auditoria') as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_result_charge_contenedor'), ['contenedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_charge_guia'), ['guia'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_charge_job_id'), ['job_id'], unique=False)

    op.create_table('result_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('guia', sa.String(length=50), nullable=False),
    sa.Column('contenedor', sa.String(length=20), nullable=False),
    sa.Column('ruta', sa.String(length=80), nullable=True),
    sa.Column('flete', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('extras', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('naviera', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['auditoria.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    with op.batch_alter_table('result_container', schema='auditoria') as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_result_container_contenedor'), ['contenedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_container_guia'), ['guia'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_container_job_id'), ['job_id'], unique=False)

    op.create_table('result_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('guia', sa.String(length=50), nullable=True),
    sa.Column('contenedor', sa.String(length=20), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('naviera', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['auditoria.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    with op.batch_alter_table('result_exception', schema='auditoria') as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_result_exception_contenedor'), ['contenedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_exception_guia'), ['guia'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_exception_job_id'), ['job_id'], unique=False)

    op.create_table('result_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('total_guias', sa.Integer(), nullable=False),
    sa.Column('guias_ok', sa.Integer(), nullable=False),
    sa.Column('guias_diferencia', sa.Integer(), nullable=False),
    sa.Column('guias_no_cerrada', sa.Integer(), nullable=False),
    sa.Column('guias_solo_en_fils', sa.Integer(), nullable=False),
    sa.Column('guias_solo_en_naviera', sa.Integer(), nullable=False),
    sa.Column('total_fils', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_naviera', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('diferencia_global', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('naviera', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['auditoria.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    with op.batch_alter_table('result_kpi', schema='auditoria') as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_result_kpi_job_id'), ['job_id'], unique=False)

    op.create_table('result_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('guia', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('total_fils', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_naviera', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('naviera', sa.String(length=30), nullable=False),
    sa.Column('fuente_naviera', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['auditoria.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auditoria'
    )
    with op.batch_alter_table('result_summary', schema='auditoria') as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_result_summary_guia'), ['guia'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_result_summary_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_summary', schema='auditoria') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_result_summary_job_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_summary_guia'))

    op.drop_table('result_summary', schema='auditoria')
    with op.batch_alter_table('result_kpi', schema='auditoria') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_result_kpi_job_id'))

    op.drop_table('result_kpi', schema='auditoria')
    with op.batch_alter_table('result_exception', schema='auditoria') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_result_exception_job_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_exception_guia'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_exception_contenedor'))

    op.drop_table('result_exception', schema='auditoria')
    with op.batch_alter_table('result_container', schema='auditoria') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_result_container_job_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_container_guia'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_container_contenedor'))

    op.drop_table('result_container', schema='auditoria')
    with op.batch_alter_table('result_charge', schema='auditoria') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_result_charge_job_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_charge_guia'))
        batch_op.drop_index(batch_op.f('ix_auditoria_result_charge_contenedor'))

    op.drop_table('result_charge', schema='auditoria')
    op.drop_table('job_files', schema='auditoria')
    op.drop_table('jobs', schema='auditoria')
    # ### end Alembic commands ###
